name: salamander_app
description: Salamander Lightning App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_core: ^1.10.0
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  cloud_functions: ^3.1.1
  flow_builder: ^0.0.9
  formz: ^0.4.1
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  coinslib: ^3.1.4
  bolt11_decoder: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - assets/images/

   
