name: flutter_shopping_cart
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.2.0
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.2.0
  mocktail: ^0.1.0

dependency_overrides:
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/images/

   
